env:
  seed: 42
  scene:
    factors:
      - variation: light_color
        enabled: True
        targets: [DefaultLightA, DefaultLightB, DefaultLightD]
        color_range: [[0.0, 0.0, 0.0], [0.5, 0.5, 0.5]]
        seed: ${env.seed}

      - variation: table_texture
        enabled: True
        seed: ${env.seed}

      - variation: table_color
        enabled: True
        color_range: [[0.25, 0.25, 0.25], [1.0, 1.0, 1.0]]
        seed: ${env.seed}

      - variation: background_texture
        enabled: True
        seed: ${env.seed}

      - variation: distractor_object
        enabled: True
        targets: [spawn_boundary0]
        num_objects: 2
        seed: ${env.seed}

      - variation: distractor_object
        enabled: True
        targets: [spawn_boundary1]
        num_objects: 2
        seed: ${env.seed}

      - variation: camera_pose
        enabled: True
        targets: [cam_front,
                  cam_over_shoulder_left,
                  cam_over_shoulder_right]
        euler_range: [[-0.05, -0.05, -0.05], [0.05, 0.05, 0.05]]
        position_range: [[-0.1, -0.1, -0.1], [0.1, 0.1, 0.1]]
        seed: ${env.seed}
